### ISSUE TITLE
Add --config CONFIG_FILE option

### ISSUE THREAD

**Issue by jcassee** [khalillechelt/grunt-compass#13]
It would be great to be able to reuse my `config.rb` file that is not located in the project root.

**Comment by khalillechelt** [comment]
Hi Joost,

can you implement it, test it with your setup and send a pull request?

Thanks

Kahlil

**Comment by jcassee** [comment]
Yes, looking at the existing code I can probably implement it. I will have
time in a few days.

**Comment by khalillechelt** [comment]
Awesome.

**Comment by jcassee** [comment]
See Pull Request #15
