### ISSUE TITLE
let the src attribute be a file as well

### ISSUE THREAD

**Issue by peter-m** [khalillechelt/grunt-compass#18]
As I would like to continue my includes via sass' @imports it's pretty annoying that the `src` parameter only accepts an entire directory and includes all files in a random order. 

See this thread why it should be avoided to include whole directories: http://stackoverflow.com/questions/4778627/is-it-possible-to-import-a-whole-directory-in-sass-using-import

**Comment by khalillechelt** [comment]
This should be done via #17

**Comment by peter-m** [comment]
How should I use it then?

My `src/css/app.scss` @imports all other scripts so I tried the following:

```
    compass: {
        dev: {
            src: 'src/css/app',
            dest: 'tmp',
            linecomments: true,
            forcecompile: true,
            //debugsass: true,
            images: 'img',
            relativeassets: true
        }
    }
```

which gives me

```
Running "compass:dev" (compass) task
>> No file matched with: src/css/app
<WARN> Task "compass:dev" failed. Use --force to continue. </WARN>
```

so I tried changing the `src` parameter to `'src/css/app.scss'` which gave me

```
Running "compass:dev" (compass) task
`compass compile src/css/app.scss --css-dir="tmp" --images-dir="img" --relative-assets --force` was initiated.

COMPASS output:
>> Error: Command failed: You must compile individual stylesheets from the project directory.
<WARN> Task "compass:dev" failed. Use --force to continue. </WARN>
```

Don't quite get how this should work - any help appreciated!

**Comment by khalillechelt** [comment]
I'll check it out tonight.

**Comment by peter-m** [comment]
somebody seems to have a similar issue [over there](https://groups.google.com/forum/?fromgroups=#!topic/compass-users/4lo5mqNVSeA) - not sure whether it's compass' fault... (I've got version 0.12.2)

**Comment by khalillechelt** [comment]
I just did a test with the newest versions of grunt, grunt-compass, sass and compass installed and it works perfectly...

**Comment by peter-m** [comment]
Running the following on Ubuntu 12.10 with grunt v0.3.17, grunt-compass v0.3.2, sass 3.3.0, compass v0.13

```
compass: {
    dev: {
        src: 'src/css/app.scss',
        dest: 'tmp',
        linecomments: true,
        forcecompile: true,
        images: 'img',
        relativeassets: true
    }
}
```

Any idea why this doesn't work? (The file exists and it's valid)

Couldn't find anything pertaining this error `Error: Command failed: You must compile individual stylesheets from the project directory.`

**Comment by Pixy** [comment]
Hello ! Did you found the answer ? I have the same problem :(

**Comment by khalillechelt** [comment]
Hi @Pixy!

I am sorry grunt-compass is deprecated and not under development anymore. Please use https://github.com/gruntjs/grunt-contrib-compass with the newest version of Grunt! 

Thank you!

**Comment by Pixy** [comment]
Yes thank you, my problem was that I specified paths thinking that the root was the sassDir
I wrote the complete path and it works now :)
