### ISSUE TITLE
@import not working right

### ISSUE THREAD

**Issue by dwilt** [khalillechelt/grunt-compass#29]
I am running into a weird bug when I am importing some files with just variables and mixins defined and then underneath those imports, I'm importing other sass files that actually use those variables and mixins and the plugin is spitting out this error:

> > Running "compass:src" (compass) task
> > `compass compile` was initiated.
> > 
> > COMPASS output:
> > error sass/global/app.sass (Line 8: Undefined variable: "$Standard".)
> > identical stylesheets/global/app.css 
> > unchanged sass/global/forms.sass
> > unchanged sass/global/mixins.sass
> > unchanged sass/global/vars.sass
> > unchanged sass/ie.sass
> > unchanged sass/pages/capture.sass
> > unchanged sass/pages/review.sass
> > unchanged sass/print.sass
> > overwrite stylesheets/screen.css 
> > Error: Command failed: 
> > <WARN> Task "compass:src" failed. Use --force to continue. </WARN>
> > 
> > Aborted due to warnings.

However, if I just run grunt again, a second time in a row, without changing any of the files, it works properly and compiles everything correctly.. See the attached image for the complete terminal output

![grunt-compass-bug](https://f.cloud.github.com/assets/1065539/8940/94739308-448e-11e2-9a83-31da28e03250.png)
:

**Comment by khalillechelt** [comment]
Nothing I can do that's a COMPASS issue not a grunt issue.

**Comment by dwilt** [comment]
But running compass compile doesn't ever throw back an error?

**Comment by khalillechelt** [comment]
Yes and grunt-compass doens't do anything but running compass compile with the specified arguments from the gruntfile. The error can only come from compass. grunt-compass doesn't parse the sass files.

Post your gruntfile if you want maybe I can see the issue there.

**Comment by dwilt** [comment]
## screen.sass

```
@import compass/reset
@import compass/css3
@import compass/utilities/general/clearfix
@import compass/typography/lists/horizontal-list

@import global/vars
@import global/mixins
@import global/forms
@import global/app

@import pages/capture
@import pages/review
```

## grunt.js

```
/*global module:false*/
module.exports = function(grunt) {

// Project configuration.
grunt.initConfig({
    compass: {
        src: 'sass',
        dest: 'stylesheets',
        outputstyle: 'expanded',
        linecomments: true,
        forcecompile: true
    },
    watch: {
        files: [ 'sass/**/*.sass' ],
        tasks: [ 'compass']
    }
});

grunt.loadNpmTasks('grunt-compass')

// Default task.
grunt.registerTask('default', 'compass');

};
```

**Comment by khalillechelt** [comment]
what happens if you set forcecompile to false? You don't need it on true as far as I can see.

Am Mittwoch, 12. Dezember 2012 um 11:57 schrieb dwilt:

**Comment by dwilt** [comment]
Still failed. Same error:

> > error sass/global/app.sass (Line 8: Undefined variable: "$Standard".)

**Comment by dwilt** [comment]
Thank you for your time Kahlil on this.

**Comment by khalillechelt** [comment]
ok and how about the line 8 in app.sass? is that variable undefined?

Am Mittwoch, 12. Dezember 2012 um 12:02 schrieb dwilt:

**Comment by dwilt** [comment]
## vars.sass

```
$Standard: Helvetica, Arial, sans-serif
$Courier: Courier, monospace

$black-primary: #333
$black-secondary: #666
$black-tertiary: #999
```

## app.sass

```
html,
body
    width: 100%
height: 100%
overflow-x: hidden

body
font: 12px/18px $Standard
```

It doesn't actually seem to be a problem though because compass DOES compile it properly every time. The problem comes when grunt is involved.

**Comment by khalillechelt** [comment]
Are you testing compass compile with the command that is generated by grunt-compass?

Am Mittwoch, 12. Dezember 2012 um 12:07 schrieb dwilt:

**Comment by dwilt** [comment]
Not sure what you mean?

**Comment by khalillechelt** [comment]
add my on Skype? username is kahlil.lechelt

**Comment by khalillechelt** [comment]
add me on Skype?  

kahlil.lechelt is the my username  

Am Mittwoch, 12. Dezember 2012 um 12:12 schrieb dwilt:

**Comment by khalillechelt** [comment]
For documentation: the problem was that the imported files didn't have underscores so they were not treated as partials.
