### ISSUE TITLE
Output file with different file name.

### ISSUE THREAD

**Issue by kvnwolf** [khalillechelt/grunt-compass#33]
Hello, i'm wondering how I can do a little trick for my develop/production environment switch. The thing is, this is my scss dir:

```
| src/
| ---- scss/
| -------- main.scss
```

If I've compress that in my dev environment, it work as expected, giving me the next input:

```
| public/
| ---- css/
| -------- main.css
```

Now, my question is: can I output a file with not the same name (ex: main.scss -> main.min.scss, foo.scss -> foo.min.scss) instead of the default name?

**Comment by khalillechelt** [comment]
Not that I know of in Compass but what you could do is use grunt to automatically rename it for instance:

This is your input:

```
| src/
| ---- scss
| -------- main.scss
```

This is your output: 

```
| output/
| ---- css
| -------- main.scss
```

And then you just configure a grunt min task that takes main.scss, minifies it and copies it to:

```
| public/
| ---- css
| -------- someothername.scss
```

**Comment by khalillechelt** [comment]
Then you create a default dev task that executes compass:dev and min:dev or something in sequence.
