### ISSUE TITLE
Creating multiple config.rb files

### ISSUE THREAD

**Issue by kvnwolf** [khalillechelt/grunt-compass#37]
Hello anyone, since i'm using the new version of Grunt (grunt-cli), the plugin isn't working correctly, it's creating me a config.rb file in each folder of the Compass project.

For example, i have the next folder structure (look at the components folder):

![Before compile](http://i48.tinypic.com/35mies7.png)

And when i compile, it creates me the config.rb **within** the components folder!

![After compile](http://i48.tinypic.com/dcx3ph.png)

That's my Gruntfile's compass snippet:

```
compass: {
    dev: {
        basePath: 'src/scss',
        config: 'src/scss/config.rb',
        src: './',
        dest: '../../public/css/dev',
        forcecompile: true
    },
    build: {
        basePath: 'src/scss',
        config: 'src/scss/config.rb',
        src: './',
        dest: '../../public/css/build',
        forcecompile: true,
        environment: 'production'
    }
}
```
#### I'm using:

grunt: ~0.4.0
grunt-compass: ~0.3.8

Help!
Thanks.

**Comment by khalillechelt** [comment]
Please start using grunt-contrib-compass! This plugin is deprecated.

**Comment by kvnwolf** [comment]
Understood, thanks for noticing.
Regards.
