### ISSUE TITLE
add --force option from compass

### ISSUE THREAD

**Issue by krzysu** [khalillechelt/grunt-compass#5]
Hi, it would be nice if I can have two grunt tasks with different config: one to watch my SASS files during development (ie. outputstyle: expanded) and second task for production build (with ie. outputstyle: compressed). And this is what I just achieved. But I miss in the production build the option to force processing of SASS files. As there aren't any changes so the compass without --force option doesn't want to reprocess files from extended to compressed style. I hope you know what I mean :)

Kris

**Comment by khalillechelt** [comment]
ah good point. thanks.  
i will have a look at that as a soon as i can.  
If you are up to it, feel free to fork and send a pull request… :)

## 

Kahlil Lechelt
http://kahlil.co

Am Dienstag, 12. Juni 2012 um 10:24 schrieb Krzysztof Urbas:

**Comment by khalillechelt** [comment]
Added the `--force` - option via the `forcecompile` - option in the gruntconfig. Please test and let me know if it does what you want.

**Comment by khalillechelt** [comment]
I also updated the Readme with an instruction.

**Comment by krzysu** [comment]
Great! It works exactly as I wished. Here is my grunt config for grunt-compass (I removed all other tasks for clarity), maybe it will help somebody, you can add it to your readme if you like https://gist.github.com/2917330

**Comment by khalillechelt** [comment]
:+1: thanks for the Gist. I will link to it in the Readme.

**Comment by khalillechelt** [comment]
https://github.com/kahlil/grunt-compass#real-world-examples
